# Generated by Django 3.2.15 on 2022-09-01 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 19, 37, 51, 331744, tzinfo=utc)),
        ),
    ]
